// Automatically generated by MockGen. DO NOT EDIT!
// Source: github.com/petrkotek/go-ash/

package core

import (
	gomock "github.com/golang/mock/gomock"
)

// Mock of EntityListener interface
type MockEntityListener struct {
	ctrl     *gomock.Controller
	recorder *_MockEntityListenerRecorder
}

// Recorder for MockEntityListener (not exported)
type _MockEntityListenerRecorder struct {
	mock *MockEntityListener
}

func NewMockEntityListener(ctrl *gomock.Controller) *MockEntityListener {
	mock := &MockEntityListener{ctrl: ctrl}
	mock.recorder = &_MockEntityListenerRecorder{mock}
	return mock
}

func (_m *MockEntityListener) EXPECT() *_MockEntityListenerRecorder {
	return _m.recorder
}

func (_m *MockEntityListener) OnEntityAdded(_param0 *Entity) {
	_m.ctrl.Call(_m, "OnEntityAdded", _param0)
}

func (_mr *_MockEntityListenerRecorder) OnEntityAdded(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "OnEntityAdded", arg0)
}

func (_m *MockEntityListener) OnEntityRemoved(_param0 *Entity) {
	_m.ctrl.Call(_m, "OnEntityRemoved", _param0)
}

func (_mr *_MockEntityListenerRecorder) OnEntityRemoved(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "OnEntityRemoved", arg0)
}
